import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612850/e-comm/man_bgremove/5-removebg-preview_seobft.png",
    title: "FERARI BlackS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 4,
    brand: "Astoria",
    inStock: true,
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "brown",
    stock: 22,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612846/e-comm/man_bgremove/14-removebg-preview_dnh5xv.png",
    title: "FOSSIL",
    price: "9000",
    mrpPrice: "18000",
    discount: "50% off",
    rating: 1,
    brand: "Asyl",
    fastDelivery: true,
    offer: ["50% off"],
    categoryName: "man",
    color: "brown",
    stock: 22,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612849/e-comm/man_bgremove/3-removebg-preview_unnfa8.png",
    title: "POLICE WAT",
    price: "1000",
    mrpPrice: "2000",
    discount: "50%",
    rating: 5,
    brand: "Soho",
    fastDelivery: true,
    offer: ["50% off"],
    categoryName: "man",
    color: "brown",
    stock: 23,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612846/e-comm/man_bgremove/12-removebg-preview_knuik0.png",
    title: "FOSSIL",
    price: "2500",
    mrpPrice: "5000",
    discount: "50%",
    rating: 4,
    brand: "Digi Sonic",
    fastDelivery: true,
    offer: ["50% off"],
    categoryName: "man",
    color: "brown",
    stock: 23,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612848/e-comm/man_bgremove/2-removebg-preview_coem9l.png",
    title: "FERARI PILOTA",
    price: "600",
    mrpPrice: "1200",
    discount: "50%",
    rating: 3,
    brand: "Abry Cmm",
    fastDelivery: true,
    offer: ["50% off"],
    categoryName: "man",
    color: "brown",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612848/e-comm/man_bgremove/28-removebg-preview_imzwd9.png",
    title: "KENNETH COLE",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 4,
    brand: "Mdh",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "brown",
    stock: 20,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612848/e-comm/man_bgremove/26-removebg-preview_osrusm.png",
    title: "FERARI TECHYNO",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 5,
    brand: "AbSx",
    fastDelivery: false,
    offer: ["60% off"],
    categoryName: "man",
    color: "brown",
    stock: 21,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612848/e-comm/man_bgremove/27-removebg-preview_tamfz9.png",
    title: "PILOTA CRONO",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612848/e-comm/man_bgremove/25-removebg-preview_od8tyx.png",
    title: "PILOTA BATN",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612847/e-comm/man_bgremove/23-removebg-preview_sqqr5v.png",
    title: "FOSSIL",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612846/e-comm/man_bgremove/17-removebg-preview_foeprh.png",
    title: "SEIKO",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612846/e-comm/man_bgremove/18-removebg-preview_iqpvia.png",
    title: "FOSSIL",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612845/e-comm/man_bgremove/10-removebg-preview_s4jztv.png",
    title: "SEIKO",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612845/e-comm/man_bgremove/9-removebg-preview_dog4ek.png",
    title: "FOSSIL GOLD",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },

  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612845/e-comm/man_bgremove/7-removebg-preview_abx3tk.png",
    title: "DW MAN",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612845/e-comm/man_bgremove/6-removebg-preview_umrynu.png",
    title: "GCMNS SA",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612845/e-comm/man_bgremove/8-removebg-preview_jhix1a.png",
    title: "HILFIGER",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "man",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },

  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612803/e-comm/woman_bgremove/13-removebg-preview_spsbvp.png",
    title: "ANNE KLEIN",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612803/e-comm/woman_bgremove/2-removebg-preview_mgigue.png",
    title: "MICHAEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612804/e-comm/woman_bgremove/4-removebg-preview_a7syu7.png",
    title: "MICHAEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612803/e-comm/woman_bgremove/3-removebg-preview_pnvcj0.png",
    title: "MICHAEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612803/e-comm/woman_bgremove/12-removebg-preview_olyx7v.png",
    title: "SKAGEN",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612803/e-comm/woman_bgremove/1-removebg-preview_xg1aly.png",
    title: "EMPORIO ARMAN",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612803/e-comm/woman_bgremove/14-removebg-preview_ftdnfo.png",
    title: "ANNE KLEIN",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612802/e-comm/woman_bgremove/11-removebg-preview_c5niqo.png",
    title: "MICHAEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612802/e-comm/woman_bgremove/7-removebg-preview_cef7me.png",
    title: "MICHAEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612802/e-comm/woman_bgremove/9-removebg-preview_gpgprb.png",
    title: "MICKEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612802/e-comm/woman_bgremove/10-removebg-preview_n25tt8.png",
    title: "MICHAEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
  {
    _id: uuid(),
    image:
      "https://res.cloudinary.com/diyo6qdy1/image/upload/v1647612802/e-comm/woman_bgremove/6-removebg-preview_r5onog.png",
    title: "MICHEL KORS",
    price: "1800",
    mrpPrice: "3800",
    discount: "60%",
    rating: 1,
    brand: "seiko",
    fastDelivery: true,
    offer: ["60% off"],
    categoryName: "woman",
    color: "Black",
    stock: 26,
    isLiked: false,
    outOfStock: false,
    isSelected: false,
  },
];
